//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchingProof.Searching {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SearchingProof.Searching.LoadDetailRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SearchingProof.Searching.LoadSearchRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IntegrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IntegrationId {
            get {
                return this.IntegrationIdField;
            }
            set {
                if ((this.IntegrationIdField.Equals(value) != true)) {
                    this.IntegrationIdField = value;
                    this.RaisePropertyChanged("IntegrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadDetailRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Searching")]
    [System.SerializableAttribute()]
    public partial class LoadDetailRequest : SearchingProof.Searching.RequestBase {
        
        private int LoadIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LoadId {
            get {
                return this.LoadIdField;
            }
            set {
                if ((this.LoadIdField.Equals(value) != true)) {
                    this.LoadIdField = value;
                    this.RaisePropertyChanged("LoadId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadSearchRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Searching")]
    [System.SerializableAttribute()]
    public partial class LoadSearchRequest : SearchingProof.Searching.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SearchingProof.Searching.LoadSearchCriteria CriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchingProof.Searching.LoadSearchCriteria Criteria {
            get {
                return this.CriteriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CriteriaField, value) != true)) {
                    this.CriteriaField = value;
                    this.RaisePropertyChanged("Criteria");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Searching")]
    [System.SerializableAttribute()]
    public partial class LoadSearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationCityField;
        
        private int DestinationRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentTypeField;
        
        private SearchingProof.Searching.LoadType LoadTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginCityField;
        
        private int OriginLatitudeField;
        
        private int OriginLongitudeField;
        
        private int OriginRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginStateField;
        
        private System.DateTime PickupDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCity {
            get {
                return this.DestinationCityField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationCityField, value) != true)) {
                    this.DestinationCityField = value;
                    this.RaisePropertyChanged("DestinationCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DestinationRange {
            get {
                return this.DestinationRangeField;
            }
            set {
                if ((this.DestinationRangeField.Equals(value) != true)) {
                    this.DestinationRangeField = value;
                    this.RaisePropertyChanged("DestinationRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationState {
            get {
                return this.DestinationStateField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationStateField, value) != true)) {
                    this.DestinationStateField = value;
                    this.RaisePropertyChanged("DestinationState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipmentType {
            get {
                return this.EquipmentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentTypeField, value) != true)) {
                    this.EquipmentTypeField = value;
                    this.RaisePropertyChanged("EquipmentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SearchingProof.Searching.LoadType LoadType {
            get {
                return this.LoadTypeField;
            }
            set {
                if ((this.LoadTypeField.Equals(value) != true)) {
                    this.LoadTypeField = value;
                    this.RaisePropertyChanged("LoadType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCity {
            get {
                return this.OriginCityField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginCityField, value) != true)) {
                    this.OriginCityField = value;
                    this.RaisePropertyChanged("OriginCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OriginLatitude {
            get {
                return this.OriginLatitudeField;
            }
            set {
                if ((this.OriginLatitudeField.Equals(value) != true)) {
                    this.OriginLatitudeField = value;
                    this.RaisePropertyChanged("OriginLatitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OriginLongitude {
            get {
                return this.OriginLongitudeField;
            }
            set {
                if ((this.OriginLongitudeField.Equals(value) != true)) {
                    this.OriginLongitudeField = value;
                    this.RaisePropertyChanged("OriginLongitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OriginRange {
            get {
                return this.OriginRangeField;
            }
            set {
                if ((this.OriginRangeField.Equals(value) != true)) {
                    this.OriginRangeField = value;
                    this.RaisePropertyChanged("OriginRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginState {
            get {
                return this.OriginStateField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginStateField, value) != true)) {
                    this.OriginStateField = value;
                    this.RaisePropertyChanged("OriginState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime PickupDate {
            get {
                return this.PickupDateField;
            }
            set {
                if ((this.PickupDateField.Equals(value) != true)) {
                    this.PickupDateField = value;
                    this.RaisePropertyChanged("PickupDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadType", Namespace="http://schemas.datacontract.org/2004/07/Truckstop2.Objects")]
    public enum LoadType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Full = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Partial = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnBase", Namespace="http://schemas.datacontract.org/2004/07/WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SearchingProof.Searching.LoadDetailReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SearchingProof.Searching.LoadSearchReturn))]
    public partial class ReturnBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SearchingProof.Searching.Error[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchingProof.Searching.Error[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadDetailReturn", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    [System.SerializableAttribute()]
    public partial class LoadDetailReturn : SearchingProof.Searching.ReturnBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SearchingProof.Searching.LoadDetailResult LoadDetailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchingProof.Searching.LoadDetailResult LoadDetail {
            get {
                return this.LoadDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadDetailField, value) != true)) {
                    this.LoadDetailField = value;
                    this.RaisePropertyChanged("LoadDetail");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadSearchReturn", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    [System.SerializableAttribute()]
    public partial class LoadSearchReturn : SearchingProof.Searching.ReturnBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SearchingProof.Searching.LoadSearchItem[] SearchResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchingProof.Searching.LoadSearchItem[] SearchResults {
            get {
                return this.SearchResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchResultsField, value) != true)) {
                    this.SearchResultsField = value;
                    this.RaisePropertyChanged("SearchResults");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Truckstop2.Objects")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadSearchItem", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    [System.SerializableAttribute()]
    public partial class LoadSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationCityField;
        
        private int DestinationDistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LengthField;
        
        private SearchingProof.Searching.LoadType LoadTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginCityField;
        
        private int OriginDistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickUpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PointOfContactPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Age {
            get {
                return this.AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeField, value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCity {
            get {
                return this.DestinationCityField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationCityField, value) != true)) {
                    this.DestinationCityField = value;
                    this.RaisePropertyChanged("DestinationCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DestinationDistance {
            get {
                return this.DestinationDistanceField;
            }
            set {
                if ((this.DestinationDistanceField.Equals(value) != true)) {
                    this.DestinationDistanceField = value;
                    this.RaisePropertyChanged("DestinationDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationState {
            get {
                return this.DestinationStateField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationStateField, value) != true)) {
                    this.DestinationStateField = value;
                    this.RaisePropertyChanged("DestinationState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipment {
            get {
                return this.EquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentField, value) != true)) {
                    this.EquipmentField = value;
                    this.RaisePropertyChanged("Equipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Length {
            get {
                return this.LengthField;
            }
            set {
                if ((object.ReferenceEquals(this.LengthField, value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SearchingProof.Searching.LoadType LoadType {
            get {
                return this.LoadTypeField;
            }
            set {
                if ((this.LoadTypeField.Equals(value) != true)) {
                    this.LoadTypeField = value;
                    this.RaisePropertyChanged("LoadType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Miles {
            get {
                return this.MilesField;
            }
            set {
                if ((object.ReferenceEquals(this.MilesField, value) != true)) {
                    this.MilesField = value;
                    this.RaisePropertyChanged("Miles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCity {
            get {
                return this.OriginCityField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginCityField, value) != true)) {
                    this.OriginCityField = value;
                    this.RaisePropertyChanged("OriginCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OriginDistance {
            get {
                return this.OriginDistanceField;
            }
            set {
                if ((this.OriginDistanceField.Equals(value) != true)) {
                    this.OriginDistanceField = value;
                    this.RaisePropertyChanged("OriginDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginState {
            get {
                return this.OriginStateField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginStateField, value) != true)) {
                    this.OriginStateField = value;
                    this.RaisePropertyChanged("OriginState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentField, value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickUpDate {
            get {
                return this.PickUpDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PickUpDateField, value) != true)) {
                    this.PickUpDateField = value;
                    this.RaisePropertyChanged("PickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointOfContactPhone {
            get {
                return this.PointOfContactPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PointOfContactPhoneField, value) != true)) {
                    this.PointOfContactPhoneField = value;
                    this.RaisePropertyChanged("PointOfContactPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((object.ReferenceEquals(this.WeightField, value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadDetailResult", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    [System.SerializableAttribute()]
    public partial class LoadDetailResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BondField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOTNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EnteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuelCostField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LengthField;
        
        private SearchingProof.Searching.LoadType LoadTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MCNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickupDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickupTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PointOfContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PointOfContactPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StopsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TMCNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckCompanyCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckCompanyEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckCompanyFaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckCompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckCompanyPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckCompanyStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Bond {
            get {
                return this.BondField;
            }
            set {
                if ((this.BondField.Equals(value) != true)) {
                    this.BondField = value;
                    this.RaisePropertyChanged("Bond");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditField, value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOTNumber {
            get {
                return this.DOTNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DOTNumberField, value) != true)) {
                    this.DOTNumberField = value;
                    this.RaisePropertyChanged("DOTNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryDate {
            get {
                return this.DeliveryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryDateField, value) != true)) {
                    this.DeliveryDateField = value;
                    this.RaisePropertyChanged("DeliveryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryTime {
            get {
                return this.DeliveryTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryTimeField, value) != true)) {
                    this.DeliveryTimeField = value;
                    this.RaisePropertyChanged("DeliveryTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCity {
            get {
                return this.DestinationCityField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationCityField, value) != true)) {
                    this.DestinationCityField = value;
                    this.RaisePropertyChanged("DestinationCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationState {
            get {
                return this.DestinationStateField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationStateField, value) != true)) {
                    this.DestinationStateField = value;
                    this.RaisePropertyChanged("DestinationState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationZip {
            get {
                return this.DestinationZipField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationZipField, value) != true)) {
                    this.DestinationZipField = value;
                    this.RaisePropertyChanged("DestinationZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((object.ReferenceEquals(this.DistanceField, value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Entered {
            get {
                return this.EnteredField;
            }
            set {
                if ((this.EnteredField.Equals(value) != true)) {
                    this.EnteredField = value;
                    this.RaisePropertyChanged("Entered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipment {
            get {
                return this.EquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentField, value) != true)) {
                    this.EquipmentField = value;
                    this.RaisePropertyChanged("Equipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuelCost {
            get {
                return this.FuelCostField;
            }
            set {
                if ((object.ReferenceEquals(this.FuelCostField, value) != true)) {
                    this.FuelCostField = value;
                    this.RaisePropertyChanged("FuelCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Length {
            get {
                return this.LengthField;
            }
            set {
                if ((object.ReferenceEquals(this.LengthField, value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SearchingProof.Searching.LoadType LoadType {
            get {
                return this.LoadTypeField;
            }
            set {
                if ((this.LoadTypeField.Equals(value) != true)) {
                    this.LoadTypeField = value;
                    this.RaisePropertyChanged("LoadType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MCNumber {
            get {
                return this.MCNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MCNumberField, value) != true)) {
                    this.MCNumberField = value;
                    this.RaisePropertyChanged("MCNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((object.ReferenceEquals(this.MileageField, value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCity {
            get {
                return this.OriginCityField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginCityField, value) != true)) {
                    this.OriginCityField = value;
                    this.RaisePropertyChanged("OriginCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginState {
            get {
                return this.OriginStateField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginStateField, value) != true)) {
                    this.OriginStateField = value;
                    this.RaisePropertyChanged("OriginState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginZip {
            get {
                return this.OriginZipField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginZipField, value) != true)) {
                    this.OriginZipField = value;
                    this.RaisePropertyChanged("OriginZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentAmount {
            get {
                return this.PaymentAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentAmountField, value) != true)) {
                    this.PaymentAmountField = value;
                    this.RaisePropertyChanged("PaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupDate {
            get {
                return this.PickupDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PickupDateField, value) != true)) {
                    this.PickupDateField = value;
                    this.RaisePropertyChanged("PickupDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupTime {
            get {
                return this.PickupTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PickupTimeField, value) != true)) {
                    this.PickupTimeField = value;
                    this.RaisePropertyChanged("PickupTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointOfContact {
            get {
                return this.PointOfContactField;
            }
            set {
                if ((object.ReferenceEquals(this.PointOfContactField, value) != true)) {
                    this.PointOfContactField = value;
                    this.RaisePropertyChanged("PointOfContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointOfContactPhone {
            get {
                return this.PointOfContactPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PointOfContactPhoneField, value) != true)) {
                    this.PointOfContactPhoneField = value;
                    this.RaisePropertyChanged("PointOfContactPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityField, value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecInfo {
            get {
                return this.SpecInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecInfoField, value) != true)) {
                    this.SpecInfoField = value;
                    this.RaisePropertyChanged("SpecInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stops {
            get {
                return this.StopsField;
            }
            set {
                if ((object.ReferenceEquals(this.StopsField, value) != true)) {
                    this.StopsField = value;
                    this.RaisePropertyChanged("Stops");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TMCNumber {
            get {
                return this.TMCNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TMCNumberField, value) != true)) {
                    this.TMCNumberField = value;
                    this.RaisePropertyChanged("TMCNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckCompanyCity {
            get {
                return this.TruckCompanyCityField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckCompanyCityField, value) != true)) {
                    this.TruckCompanyCityField = value;
                    this.RaisePropertyChanged("TruckCompanyCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckCompanyEmail {
            get {
                return this.TruckCompanyEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckCompanyEmailField, value) != true)) {
                    this.TruckCompanyEmailField = value;
                    this.RaisePropertyChanged("TruckCompanyEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckCompanyFax {
            get {
                return this.TruckCompanyFaxField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckCompanyFaxField, value) != true)) {
                    this.TruckCompanyFaxField = value;
                    this.RaisePropertyChanged("TruckCompanyFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckCompanyName {
            get {
                return this.TruckCompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckCompanyNameField, value) != true)) {
                    this.TruckCompanyNameField = value;
                    this.RaisePropertyChanged("TruckCompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckCompanyPhone {
            get {
                return this.TruckCompanyPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckCompanyPhoneField, value) != true)) {
                    this.TruckCompanyPhoneField = value;
                    this.RaisePropertyChanged("TruckCompanyPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckCompanyState {
            get {
                return this.TruckCompanyStateField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckCompanyStateField, value) != true)) {
                    this.TruckCompanyStateField = value;
                    this.RaisePropertyChanged("TruckCompanyState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((object.ReferenceEquals(this.WeightField, value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Width {
            get {
                return this.WidthField;
            }
            set {
                if ((object.ReferenceEquals(this.WidthField, value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.truckstop.com/v2", ConfigurationName="Searching.ILoadSearch")]
    public interface ILoadSearch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v2/ILoadSearch/GetLoadSearchResults", ReplyAction="http://webservices.truckstop.com/v2/ILoadSearch/GetLoadSearchResultsResponse")]
        SearchingProof.Searching.LoadSearchReturn GetLoadSearchResults(SearchingProof.Searching.LoadSearchRequest searchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v2/ILoadSearch/GetLoadSearchDetailResult", ReplyAction="http://webservices.truckstop.com/v2/ILoadSearch/GetLoadSearchDetailResultResponse" +
            "")]
        SearchingProof.Searching.LoadDetailReturn GetLoadSearchDetailResult(SearchingProof.Searching.LoadDetailRequest detailRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoadSearchChannel : SearchingProof.Searching.ILoadSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadSearchClient : System.ServiceModel.ClientBase<SearchingProof.Searching.ILoadSearch>, SearchingProof.Searching.ILoadSearch {
        
        public LoadSearchClient() {
        }
        
        public LoadSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoadSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SearchingProof.Searching.LoadSearchReturn GetLoadSearchResults(SearchingProof.Searching.LoadSearchRequest searchRequest) {
            return base.Channel.GetLoadSearchResults(searchRequest);
        }
        
        public SearchingProof.Searching.LoadDetailReturn GetLoadSearchDetailResult(SearchingProof.Searching.LoadDetailRequest detailRequest) {
            return base.Channel.GetLoadSearchDetailResult(detailRequest);
        }
    }
}
